[package]
name = "tag"
version = "0.1.0"
authors = ["Johannes Vallikivi <j.vallikivi@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
piston = "0.49.0"
piston2d-graphics = "0.36.0"
pistoncore-glutin_window = "0.63.0"
piston2d-opengl_graphics = "0.72.0"
rayon = "1.3.0"